---
- block:
  - name: download and unpack OpenMPI
    unarchive: 
      src: "https://download.open-mpi.org/release/open-mpi/v{{ openmpi_release }}/openmpi-{{ openmpi_version }}.tar.gz"
      dest: /tmp/
      remote_src: yes

  - name: configure and build OpenMPI
    shell: |
      source /opt/rh/devtoolset-9/enable
      ./configure --prefix=/opt/openmpi-{{ openmpi_version }} --with-ucx=/opt/{{ mellanox_hpcx_package }}/ucx/ --with-hcoll=/opt/{{ mellanox_hpcx_package }}/hcoll --enable-mpirun-prefix-by-default --with-platform=contrib/platform/mellanox/optimized && make -j && make install
    args: 
      chdir: "/tmp/openmpi-{{ openmpi_version }}"
      creates: "/opt/openmpi-{{ openmpi_version }}"

  - name: Install OpenMPI module file
    template:
      src: templates/module.j2
      dest: "/usr/share/Modules/modulefiles/mpi/openmpi-{{ openmpi_version }}-gcc9"
      owner: root
      group: root
      mode: '0644'
