---
- block: 

  - name: Extract HPC-X
    unarchive: 
      src: "{{ mellanox_hpcx_download_url }}"
      dest: "{{ install_prefix }}"
      remote_src: yes
      creates: "{{ install_prefix }}/{{ mellanox_hpcx_package}}"

  - name: Create MPI directory
    file:
      path: /usr/share/Modules/modulefiles/mpi/
      state: directory

  - name: Create HPCX module file
    template: 
      dest: "/usr/share/Modules/modulefiles/mpi/hpcx-{{ hpcx_version }}"
      src: templates/module.j2
      owner: root
      group: root
      mode: 0644

  - name: Create HPCX module symlink
    file: 
      src: "/usr/share/Modules/modulefiles/mpi/hpcx-{{ hpcx_version }}"
      dest: /usr/share/Modules/modulefiles/mpi/hpcx
      state: link
      force: yes
