---
- block: 

  - name: Download Mellanox HPC-X
    get_url: url="http://content.mellanox.com/hpc/hpc-x/v2.6/hpcx-v2.6.0-gcc-MLNX_OFED_LINUX-5.0-1.0.0.0-redhat7.7-x86_64.tbz" dest="/tmp"
    when: ofed_version is failed or ofed_version.stdout != mellanox_ofed_version

  - name: Extract HPC-X
    unarchive: 
      src: /tmp/hpcx-v2.6.0-gcc-MLNX_OFED_LINUX-5.0-1.0.0.0-redhat7.7-x86_64.tbz
      dest: /tmp/
      remote_src: yes
    when: ofed_version is failed or ofed_version.stdout != mellanox_ofed_version

#  - name: Install OFED
#    command: chdir="/tmp/MLNX_OFED_LINUX-{{ mellanox_ofed_version }}-ol{{ os_version }}-x86_64" ./mlnxofedinstall --kernel {{ ansible_kernel }} --kernel-sources /usr/src/kernels/{{ ansible_kernel }} --add-kernel-support --skip-repo --skip-distro-check
#    when: ofed_version is failed or ofed_version.stdout != mellanox_ofed_version
#
  vars: 
    os_version: "{{ '7.7' if ansible_distribution_version else ansible_distribution_version }}"

- block: 
#
# Copy the required fles
#
#  - name: Copy /opt/oci-hpc/sbin
#    copy: 
#      src: files/sbin 
#      dest: /opt/oci-hpc/
#      mode: 0755
#      group: root
#      owner: root
#      directory_mode:
#
#  - name: Copy /opt/oci-hpc/bin
#    copy: 
#      src: files/bin 
#      dest: /opt/oci-hpc/
#      mode: 0755
#      group: root
#      owner: root
#      directory_mode:
#
#  - name: Install WPA certs cron script
#    cron: 
#      name: "update wpa certs"
#      user: root
#      job: "/opt/oci-hpc/sbin/update_wpa_certs.py"
#      cron_file: update_wpa_certs
#      minute: "*/15"
#
#  - name: Install ifup-local symlink
#    file:
#     src: /opt/oci-hpc/sbin/ifup-local
#      dest: /usr/sbin/ifup-local
#      owner: root
#      group: root
#      state: link
#      mode: '0755'
#
#
